site_name: {{ cookiecutter.project_slug }}

site_url: https://{{ cookiecutter.github_username }}.github.io/{{ cookiecutter.project_slug }}

repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
        features:
            - instant
            - navigation.expand
            - tabs
            - search.highlight

plugins:
    - search
    - mkdocstrings
    - git-revision-date

markdown_extensions:
    - attr_list

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/issues
    - API Reference:
          - {{ cookiecutter.project_slug }} module: {{ cookiecutter.project_slug }}.md
