site_name: pkg-creator

site_url: https://giswqs.github.io/pkg-creator

repo_url: https://github.com/giswqs/pkg-creator

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
        features:
            - instant
            - navigation.expand
            - tabs
            - search.highlight

plugins:
    - search
    - mkdocstrings
    - git-revision-date

markdown_extensions:
    - attr_list

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/giswqs/pkg-creator/issues
    - API Reference:
          - pkg-creator module: pkg-creator.md
